language: node_js
node_js:
  - node
build:
  script:
    - npm run build
deploy:
  provider: s3
  access_key_id: "$DIGITAL_OCEAN_SPACES_KEY_ID"
  secret_access_key: "$DIGITAL_OCEAN_SPACES_ACCESS_KEY"
  bucket: "$DIGITAL_OCEAN_SPACES_BUCKET"
  endpoint: "$DIGITAL_OCEAN_SPACES_ENDPOINT"